### DISCUSSION TITLE
Render template with message as variables

### DISCUSSION THREAD

**Discussion by Splint77** [zachowj/node-red-contrib-home-assistant-websocket#1443] [Q&A]
I'm trying to use a `render template` to genere a text based on the template and variables I pass along to it. I'm not sure if it should be possible.
I assume the input message is / can be passed along to the Home Assistant Websocket or rest api call as variables under the hood.

I see indications in the home assistant core api that variables can be passed along to template api.
https://github.com/home-assistant/core/blob/19c26b79afb08268286c5fdc93d0d00a8c6d52e2/homeassistant/components/api/__init__.py#L441-L457

I have put together a small basic example where a json object with a property named myname is injected into the `render template`. The returned message is not 'Name: Donald Dock' as I had hoped.

```
[{"id":"737c0e77a1107c7d","type":"inject","z":"0572ae7acecd5102","name":"Inject myname","props":[{"p":"payload"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"{\"myname\":\"Donald Duck\"}","payloadType":"json","x":240,"y":1240,"wires":[["4b450bc6e2be2eaf"]]},{"id":"4b450bc6e2be2eaf","type":"api-render-template","z":"0572ae7acecd5102","name":"Render template with myname variable","server":"","version":0,"template":"Name: {{myname}}","resultsLocation":"payload.message","resultsLocationType":"msg","templateLocation":"","templateLocationType":"none","x":510,"y":1240,"wires":[["9ed7fe6f2c6a90b9"]]},{"id":"9ed7fe6f2c6a90b9","type":"debug","z":"0572ae7acecd5102","name":"Rendered template message","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","statusVal":"","statusType":"auto","x":840,"y":1240,"wires":[]}]
```

My end goal is to apply code in Node-Red like the following from the Alarmo project where the trigger.event.data.sensors is used inside the Jinja2 code to generate the message:
```
trigger:
  - platform: event
    event_type: alarmo_failed_to_arm
condition:
  - condition: template
    value_template: '{{ trigger.event.data.reason == ''open_sensors'' }}'
action:
  - service: notify.mobile_app_my_phone
    data:
      message: >
        Could not arm because of the following problems:
        {% for entity_id in trigger.event.data.sensors %}
          - {{ state_attr(entity_id, 'friendly_name') }} is {{ states(entity_id) }}
        {% endfor %}
      title: test
```
Source: https://github.com/nielsfaber/alarmo/tree/main
