### DISCUSSION TITLE
error connecting -- no logged output

### DISCUSSION THREAD

**Discussion by clifton** [zachowj/node-red-contrib-home-assistant-websocket#438] [Q&A] [answered]
tried:
- checking the "i use the home assistant addon"
- using the localhost:8123 url
- using the remote nubu.casa url

i get no log output on either node-red or homeassistant. im using the docker containers FWIW (compose.yml below)

![image](https://user-images.githubusercontent.com/14217/124787668-4845c400-df0e-11eb-95f7-353f7e471929.png)

![image](https://user-images.githubusercontent.com/14217/124787741-5b589400-df0e-11eb-9808-9ccd2c682cdd.png)

```yaml
version: '3'
services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/raspberrypi4-homeassistant:stable"
    volumes:
      - ./config:/config
      - /etc/localtime:/etc/localtime:ro
      - /dev/zwave:/dev/zwave
      - /dev/zigbee:/dev/zigbee
    restart: unless-stopped
    privileged: true
    network_mode: host

  node-red:
    build: node-red/
    user: root
    environment:
      - TZ=America/Chicago
    # ports:
    #   - "1880:1880"
    network_mode: host
    volumes:
      - ./node-red:/data
```

```Dockerfile
FROM nodered/node-red:latest

RUN npm install \
    node-red-contrib-actionflows \
    # https://flows.nodered.org/node/node-red-contrib-actionflows
    node-red-contrib-home-assistant-websocket \
    # https://flows.nodered.org/node/node-red-contrib-home-assistant-websocket
    node-red-contrib-stoptimer \
    # https://flows.nodered.org/node/node-red-contrib-stoptimer
    node-red-contrib-time-range-switch \
    # A simple Node-RED node that routes messages depending on the
    # time. If the current time falls within the range specified in the node
    # configuration, the message is routed to output 1. Otherwise the message
    # is routed to output 2.
    node-red-contrib-timecheck \
    # Is it that time yet? This node compares a given time to the current time.
    node-red-node-timeswitch
    # node to provide a simple timeswitch node to schedule daily on/off events
```
