### DISCUSSION TITLE
Targeting areas in service calls

### DISCUSSION THREAD

**Discussion by davosian** [zachowj/node-red-contrib-home-assistant-websocket#440] [Q&A]
I would like to call a service which targets an area instead of an entity id like this:

```yaml
service: media_player.volume_set
data:
  volume_level: 0.2
target:
  area_id: bad
```

However, if I understand the `call service` node correctly, I can only set an `entity id` and information inside `data`, but I cannot add the `target` section. Am I missing something?

**Comment by davosian** [comment]
It looks like the following syntax works inside the `data` field:

```yaml
{
    "volume_level": 0.2,
    "area_id": "bad"
}
```

Is this the correct way of doing it?
