### DISCUSSION TITLE
Support Call Service targets in HA

### DISCUSSION THREAD

**Discussion by rvaidya** [zachowj/node-red-contrib-home-assistant-websocket#481] [Feature Request]
Home Assistant service calls allow you to specify area ids and device ids in addition to entity ids using the target attribute:

https://www.home-assistant.io/docs/scripts/service-calls/#targeting-areas-and-devices

Ex:

```
service: light.turn_on
target:
  area_id: living_room
  device_id:
    - ff22a1889a6149c5ab6327a8236ae704
    - 52c050ca1a744e238ad94d170651f96b
  entity_id:
    - light.hallway
    - light.landing
```

Being able to target areas would help a lot in creating automations and would gain some ground towards resolving https://github.com/zachowj/node-red-contrib-home-assistant-websocket/issues/91

Targeting devices for service calls is a little less useful from my limited experience, but I do have some devices that do not publish any entities and only work with the alpha device trigger (for triggers only).
