### DISCUSSION TITLE
Can't find or connect to Home Assistant

### DISCUSSION THREAD

**Discussion by Jiheffe** [zachowj/node-red-contrib-home-assistant-websocket#501] [Q&A]
Hi, 
I have Node-RED and Home Assistant each running in their docker container...
I try to set up the Home Assistant server per [these instructions](https://zachowj.github.io/node-red-contrib-home-assistant-websocket/guide/#using-npm-from-the-command-line). I can't find the server with the search button, so I configure it manually: `http://192.168.2.60:8123`.
When I then try to deploy, the box under the node stays on orange `Connecting`...
In the Node-RED log, I just get 
```
95bf883801cc_nodered | 28 Oct 21:18:49 - [info] Stopped flows
95bf883801cc_nodered | 28 Oct 21:18:49 - [info] Starting flows
95bf883801cc_nodered | 28 Oct 21:18:49 - [info] Started flows
95bf883801cc_nodered | 28 Oct 21:18:49 - [info] [server:Home Assistant] Connecting to http://192.168.2.60:8123
95bf883801cc_nodered | 28 Oct 21:19:56 - [info] [server:Home Assistant] Connecting to http://192.168.2.60:8123
95bf883801cc_nodered | 28 Oct 21:21:04 - [info] [server:Home Assistant] Connecting to http://192.168.2.60:8123
95bf883801cc_nodered | 28 Oct 21:22:11 - [info] [server:Home Assistant] Connecting to http://192.168.2.60:8123
95bf883801cc_nodered | 28 Oct 21:23:19 - [info] [server:Home Assistant] Connecting to http://192.168.2.60:8123
```
This is my Node-RED `docker-compose.yml` file:
```
version: "3.7"

services:
  node-red:
    container_name: nodered
    image: nodered/node-red:latest
    environment:
      - TZ=Europe/Brussels
    ports:
      - "1880:1880"
    restart: unless-stopped
    volumes:
      - ./data:/data

```
And this is my Home Assistant `docker-compose.yml`:

```
version: '3'
services:
  homeassistant:
    container_name: homeassistant
    image: homeassistant/home-assistant:stable
    volumes:
      - ./config:/config
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
    devices:
      # Conbee II Zigbee device on USB
      - /dev/ttyACM1:/dev/ttyACM1
    restart: unless-stopped
    network_mode: host

```

Can anyone tell me what I am missing ?
