### DISCUSSION TITLE
Trigger node with "for" duration

### DISCUSSION THREAD

**Discussion by anthonyma94** [zachowj/node-red-contrib-home-assistant-websocket#698] [General]
I have this trigger in HA that I'd like to reproduce:

```yaml
platform: state
entity_id: binary_sensor.upstairs_sensors
from: "on"
to: "off"
for: >-
  {% if states('input_select.mode') == 'Day' %}  00:00:20{% else %}  00:05:00{%
  endif %}
```

My problem is that the event: state node only accepts a number value, and the trigger node doesn't have a for duration option. How can I reproduce this?
