### ISSUE TITLE
Help, time threshold trigger

### ISSUE THREAD

**Issue by stkang** [zachowj/node-red-contrib-home-assistant-websocket#146]
I want to create an automation code like below.
But I don't know how.

```
 for:
  seconds: 60
```

09:00:00,  motion on (switch.turn_on)
09:00:30, -> motion off (30s)
09:00:40, -> motion on (10s)
09:01:40, -> motion off (60s)
09:01:40, -> switch.turn_off

Triggers when numeric value of an entity’s state crosses a given threshold

```
- alias: 'Bathroom Light Off'
    trigger:
      platform: state
      entity_id: sensor.bathroom_motion
      to: "inactive"
      for:
        seconds: 60
    action:
      - service: switch.turn_off
        entity_id: switch.bathroom_light
```
