### ISSUE TITLE
"HomeAssistantError: extra keys not allowed ..." when action node is fired

### ISSUE THREAD

**Issue by skynet01** [zachowj/node-red-contrib-home-assistant-websocket#1588]
### Describe the bug

When I use an action (used to be service) call node and use the google_generative_ai_conversation.generate_content call which requires the "prompt" key in data it no longer works and I get 2 errors:" 

`"The domain and service input properties are deprecated and will be removed in version 1.0. Please use the action property instead."`

and 

`"HomeAssistantError: extra keys not allowed @ data['prompt']"`

This used to work before and calling it directly from HA works:

```
action: google_generative_ai_conversation.generate_content
data:
  prompt: Describe what you see in these images
  image_filename: /config/www/image.jpg
```

### To Reproduce

Make an action node, set action to google_generative_ai_conversation.generate_content 
Click the fill in demo data to prefill the data, inject it with timestamp. 

### Expected behavior

node should execute correctly, or at least will give you an error about incorrect image path :) 

### Screenshots

![image](https://github.com/user-attachments/assets/f4da1072-802b-459c-a2d5-f0ef095c73a2)

### Environment Information

Version: 0.72.4

Home Assistant version: 2024.9.2
Companion version: 0.0.0

Node-RED version: 4.0.2
Docker: yes
Add-on: 18.0.5

Node.js version: v18.20.3 arm linux
OS: Linux 5.10.103-v7l+ arm
