### ISSUE TITLE
Calendar get_events not working

### ISSUE THREAD

**Issue by jq-yeraz** [zachowj/node-red-contrib-home-assistant-websocket#1683]
### Describe the bug

In home assistant, I call the calendar.get_events action with the next data : 

```
action: calendar.get_events
target:
  entity_id: calendar.poubelles
data:
  start_date_time: "2024-11-04 00:00:00"
  end_date_time: "2024-11-10 00:00:00"
```

The service return some result corresponding to the selected entity. Example :

```
calendar.poubelles:
  events:
    - start: "2024-11-06"
      end: "2024-11-07"
      summary: Poubelle jaune
      description: "
```

I use exactly the same parameters (with a JSONata expression) in node red with the action node manually triggered : 

```
{ 
 "start_date_time" : "2024-11-04 00:00:00",
 "end_date_time":"2024-11-10 00:00:00"
}
```

Below the debug information :

```
object
  domain: "calendar"
  service: "get_events"
  target: object
    entity_id: "calendar.poubelles"
  data: object
    start_date_time: "2024-11-04 00:00:00"
    end_date_time: "2024-11-10 00:00:00"
```

The action return no events : 

```
object
  _msgid: "5d094a76252cf720"
  payload: 1730924536853
```

I try with other format like "2024-11-04T00:00:00.000Z" but same result.

### Environment Information

Version: 0.74.2

Home Assistant version: 2024.10.4
Companion version: 0.0.0

Node-RED version: 4.0.5
Docker: no
Add-on: no

Node.js version: v18.19.1 x64 linux
OS: Linux 6.8.12-2-pve x64
