### ISSUE TITLE
HA Palette disappears on NR container reboot

### ISSUE THREAD

**Issue by MeatSuitBattery** [zachowj/node-red-contrib-home-assistant-websocket#862]
### Describe the bug

Summary (this is being submitted as one bug because it 'feels' related):
- v0.48.1 not installing from Manage Palettes
- v0.42.8 and 0.33.1 (only 2 tested) can be installed from Manage Palettes if first installed with npm. Apparently not v0.48.1. 
- on reboot of NR container, HA Palette disappears, but other installed nodes, such as node-red-node-wol, remain persistent between restarts.
- the above has been repeated on 2 freshly deployed docker instances, on the same hardware, on the same day.

### To Reproduce

I am building a rpi4 8gb project, with a 32gb sd card, which has been flashed with the retropie-buster-4.8-rpi4_400.img.gz as the host. 

I am following this tutorial for building the docker containers, and I am currently stuck on pg5 trying to install this NR websock: 
https://sequr.be/blog/2022/08/home-assistant-container-part-1-install-debian-docker-and-portainer/

Due to my project using a 32bit OS, and the above tutorial being based on a 64bit OS, some docker images have been changed from the tutorial. Also, apparently NR3 is not rpi compatible currently. 

docker-compose.yaml (location obscured):
```
version: '3.0'

services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    restart: unless-stopped
    ports:
      - "9000:9000/tcp"
      - "9443:9443/tcp"
    environment:
      - TZ=Americia/********
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/portainer/data:/data

  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    restart: unless-stopped
    environment:
      - TZ=Americia/********
    volumes:
      - /opt/homeassistant/config:/config
      - /etc/localtime:/etc/localtime:ro
    privileged: true
    network_mode: host
    depends_on:
      - mariadb
      - influxdb
      - mosquitto
	  
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883/tcp"
    environment:
      - TZ=Americia/********
    volumes:
      - /opt/mosquitto/config:/mosquitto/config
      - /opt/mosquitto/data:/mosquitto/data
      - /opt/mosquitto/log:/mosquitto/log
    stdin_open: true
    tty: true

  nodered:
    container_name: nodered
#    image: nodered/node-red
#   https://github.com/node-red/node-red-docker/issues/319
    image: nodered/node-red:2.2.2
    restart: unless-stopped
    ports:
      - "1880:1880/tcp"
    environment:
      - TZ=Americia/********
    volumes:
      - /opt/nodered/data:/data
    depends_on:
      - homeassistant
      - mosquitto
	  
  adminer:
    container_name: adminer
    image: adminer
    restart: unless-stopped
    ports:
      - "8080:8080/tcp"
    depends_on:
      - mariadb
	  
  mariadb:
    container_name: mariadb
    image: linuxserver/mariadb:latest
    restart: unless-stopped
    ports:
      - "3306:3306/tcp"
    environment:
      - TZ=Americia/********
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_HA_DATABASE}
      - MYSQL_USER=${MYSQL_HA_USER}
      - MYSQL_PASSWORD=${MYSQL_HA_PASSWORD}
    volumes:
      - /opt/mariaDB/data:/var/lib/mysql
      - /opt/mariaDB/config/:/etc/mysql/conf.d

  influxdb:
    container_name: influxdb
    image:  arm32v7/influxdb:latest
    restart: unless-stopped
    ports:
#      - "8086:8086/tcp"
# So we can access the WebUI
    environment:
      - TZ=Americia/********
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUXDB_USER}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUXDB_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUXDB_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUXDB_BUCKET}
    volumes:
      - /opt/influxDB/data:/var/lib/influxdb2
      - /opt/influxDB/config/:/etc/influxdb2
    ulimits:
      nofile:
        soft: 32768
        hard: 32768

```

- node-red-contrib-home-assistant-websocket (@0.48.1) cannot be installed from Manage Palettes. This produces the following log:
```
2023-02-05T07:22:50.025Z Install : node-red-contrib-home-assistant-websocket 0.48.1

2023-02-05T07:22:50.987Z npm install --no-audit --no-update-notifier --no-fund --save --save-prefix=~ --production --engine-strict node-red-contrib-home-assistant-websocket@0.48.1
2023-02-05T07:23:05.943Z [err] npm
2023-02-05T07:23:05.944Z [err]  
2023-02-05T07:23:05.944Z [err] WARN
2023-02-05T07:23:05.944Z [err]  
2023-02-05T07:23:05.944Z [err] optional
2023-02-05T07:23:05.945Z [err]  SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.3.2 (node_modules/chokidar/node_modules/fsevents):
2023-02-05T07:23:05.946Z [err] npm
2023-02-05T07:23:05.946Z [err]  
2023-02-05T07:23:05.947Z [err] WARN
2023-02-05T07:23:05.947Z [err]  
2023-02-05T07:23:05.947Z [err] notsup
2023-02-05T07:23:05.948Z [err]  SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm"})
2023-02-05T07:23:05.949Z [err] 
2023-02-05T07:23:05.952Z [out] + node-red-contrib-home-assistant-websocket@0.48.1
2023-02-05T07:23:05.952Z [out] updated 1 package in 13.488s
2023-02-05T07:23:05.996Z rc=0
```

If I use Portainer to access the NR CLI, I can manually run the following without error:
`npm install --no-audit --no-update-notifier --no-fund --save --save-prefix=~ --production --engine-strict node-red-contrib-home-assistant-websocket@0.42.8`

This does not make the HA Palette available in NR. 
If I then use Manage Palettes to install node-red-contrib-home-assistant-websocket, this will install successfully install v0.42.8, and the HA Palette will now be available. 

On rebooting the NR container with Portainer, the HA Palette disappears. 
In data/node_modules/ there is still a node-red-contrib-home-assistant-websocket directory. 

The npm-then-Manage-Palette method was also tested with the same results with v0.33.1.
v0.48.1 could not be installed with the npm-then-Manage-Palette method.

With at least v0.42.8, after the npm-then-Manage-Palette method, it could successfully be updated to v0.48.1 from Manage-Palette, but this would still be lost on container restart like all other situations.

### Expected behavior

Pressing install in Manage-Palette, and it installs; and it is still working after a restart? 
(I'm not sure what to say here)

### This package's version (not the Home Assistant add-on version)

0.33.1, 0.42.8, 0.48.1

### Is Node-RED running in Docker?

Yes

### Node-RED version

2.2.2

### Node.js version

14.18.2

### Additional context

A lot of this is new to me, please be gentle.  

***Edit:
After the NR container has had the websock installed, and has been rebooted, the websock can be reinstalled from Manage Palette on subsequent restarts.
***Edit2
If v0.42.8 is installed as described above, and NR is restarted, it can be reinstalled Manage Palette. But if v0.42.8 is upgraded to v0.48.1, on subsequent restarts, Manage Palette will install v0.42.8.

On some Manage Palette reinstalls after a restart, a first reinstall attempt will fail, but second attempt will succeed. so far no more than 2 attempts have been needed to reinstall after a restart, through Manage Palette.
